name: caretaker_wellnest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.4
  intl: ^0.17.0
  flutter_holo_date_picker: ^2.0.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  permission_handler: ^11.4.0
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - asset/
