name: family_member
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  image_picker: ^1.0.4
  supabase_flutter: ^2.8.3
  file_picker: ^9.0.0
  flutter_secure_storage: ^9.2.4
  flutter_cashfree_pg_sdk: ^2.2.4+42
  razorpay_flutter: ^1.3.7
  http: ^1.2.0
  fluttertoast: ^8.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - asset/

